{% raw %}
{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version') %}

package:
  name: access-nri-intake
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/a/access-nri-intake/access_nri_intake-{{ version }}.tar.gz"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

{% endraw %}
requirements:
  host:
    - python
    - pip
    - versioneer
  run:
    - python >=3.10
    - pip>=24.0
    - wheel==0.33.6
    - watchdog==0.9.0
    - tox>=4.0
    - coverage>=7.0.0
    - sphinx>=8.0
    - twine>=6.0.0
    {%- if cookiecutter.use_ruff == 'y' %}
    - ruff>=0.9
    {%- endif %}
    {%- if cookiecutter.use_mypy == 'y' %}
    - mypy>=1.15
    {%- endif %}
    {%- if cookiecutter.command_line_interface|lower == 'click' %}
    - click==7.1.2
    {%- endif %}
    {%- if cookiecutter.use_pytest == 'y' %}
    - pytest==6.2.4
    {%- endif %}
    - pip:
      - codecov

about:
  home: https://github.com/{{cookiecutter.__gh_slug}}
  license: {{cookiecutter.open_source_license}}
  summary: {{cookiecutter.project_short_description}}
  doc_url: https://access-nri-intake-catalog.readthedocs.io/en/latest/

extra:
  recipe-maintainers: