name: {{cookiecutter.project_slug}}-3.13
channels:
  - conda-forge
  - accessnri
  - defaults
dependencies:
  - python==3.13
  - pip>=24.0
  - wheel==0.33.6
  - watchdog==0.9.0
  - tox>=4.0
  - coverage>=7.0.0
  - sphinx>=8.0
  - twine>=6.0.0
  {%- if cookiecutter.use_ruff == 'y' %}
  - ruff>=0.9
  {%- endif %}
  {%- if cookiecutter.use_mypy == 'y' %}
  - mypy>=1.15
  {%- endif %}
  {%- if cookiecutter.command_line_interface|lower == 'click' %}
  - click==7.1.2
  {%- endif %}
  {%- if cookiecutter.use_pytest == 'y' %}
  - pytest==6.2.4
  {%- endif %}
  - pip:
    - codecov