name: CI

on: [pull_request, push, workflow_dispatch]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniconda-version: "latest"
            python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
            environment-file: ci/environment-{% raw %}${{ matrix.python-version }}{% endraw %}.yml
            activate-environment: {{ cookiecutter.project_slug }}-{% raw %}${{ matrix.python-version }}{% endraw %}
            auto-activate-base: false

      - name: Install source
        shell: bash -l {0}
        run: python -m pip install .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run tests
        shell: bash -l {0}
        run: coverage run -m --source={{cookiecutter.project_slug}} pytest tests
      
      - name: Generate coverage report
        shell: bash -l {0}
        run: coverage xml

      - name: Upload code coverage
        uses: codecov/codecov-action@v5
        with:
          token: {% raw %} ${{ secrets.codecov_token }} {% endraw %}
          files: ./coverage.xml